const EXAMPLE_ACTION_TYPES = {
  GET_API_CALL: 'GET_API_CALL',
  GET_API_DATA: 'GET_API_DATA',
  POST_API_CALL: 'POST_API_CALL',
  POST_API_DATA: 'POST_API_DATA'
};

export default EXAMPLE_ACTION_TYPES;
